/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InputPanel.java
 *
 * Created on Nov 1, 2010, 7:20:15 PM
 */

package map;

import java.util.*;
import java.text.*;

import org.jdesktop.swingx.*;
import org.jdesktop.swingx.mapviewer.*;

import map.object.*;
import map.util.*;

/**
 *
 * @author Alex
 */
public class InputPanel extends javax.swing.JPanel {

    protected InputMap inputMap = null;

    /** Creates new form InputPanel */
    public InputPanel() {
        initComponents();
    }

    /** Creates new form InputPanel */
    public InputPanel(InputMap inputMap) {
        initComponents();
        init();
    }

    public void setInputMap(InputMap inputMap) {
        this.inputMap = inputMap;
        init();
    }

    protected void init() {
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yy HH:mm");
        this.jTextField1.setText(sdf.format(new Date()));
        inputMap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if ((evt.getButton() == evt.BUTTON1)) {
                    JXMapViewer mv = inputMap.getJXMapViewer();
                    GeoPosition gp = mv.convertPointToGeoPosition(evt.getPoint());
                    if (jRadioButton1.isSelected()) {
                        MapBuoy mb = new MapBuoy(mv, gp);
                        mb.getJObject().setLabel("B:" + new Long(mb.getNumber()).toString() + ":" + gp);
                        mb.setRadius(jSlider1.getValue());
                        mv.repaint();
                    }
                    else if(jRadioButton2.isSelected()) {
                        MapCircularObstacle mco = new MapCircularObstacle(mv, gp);
                        mco.getJObject().setLabel("O:" + gp);
                        mco.setRadius(jSlider1.getValue());
                        mv.repaint();
                    }
                    else if(jRadioButton3.isSelected()) {
                        MapWayPoint mwp = new MapWayPoint(mv, gp);
                        mwp.getJObject().setLabel("WP:" + new Long(mwp.getNumber()).toString() + ":" + gp);
                        mwp.setRadius(jSlider1.getValue());
                        mv.repaint();
                    }
                    else if(jRadioButton4.isSelected()) {
                        MapWayPoint mwp = new MapAutoWayPoint(mv, gp);
                        mwp.getJObject().setLabel("AWP:" + new Long(mwp.getNumber()).toString() + ":" + gp);
                        mwp.setRadius(jSlider1.getValue());
                        mv.repaint();
                    }
                    else if(jRadioButton5.isSelected()) {
                        Calendar c = new GregorianCalendar();
                        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yy HH:mm");
                        try {
                            c.setTime(sdf.parse(jTextField1.getText()));
                        }
                        catch (Exception e) {
                            e.printStackTrace();
                        }
                        MapTimerWayPoint mwp = new MapTimerWayPoint(mv, gp, c);
                        mwp.getJObject().setLabel("TWP:" + new Long(mwp.getNumber()).toString() + ":" + gp + ":" + c.getTime());
                        mwp.setRadius(jSlider1.getValue());
                        mv.repaint();
                    }
                }
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSlider1 = new javax.swing.JSlider();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(60, 18));

        jSlider1.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jSlider1.setMajorTickSpacing(100);
        jSlider1.setMaximum(2000);
        jSlider1.setMinorTickSpacing(50);
        jSlider1.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Obstacle");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("WayPoint");

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("AutoWayPoint");

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setText("TimerWayPoint");
        jRadioButton5.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton5StateChanged(evt);
            }
        });

        jTextField1.setText("01.10.10 16:00");
        jTextField1.setEnabled(false);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Buoy");

        jLabel2.setText("Object Type");

        jLabel1.setText("Radius");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jRadioButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButton4, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSlider1, 0, 0, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton5StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton5StateChanged
        // TODO add your handling code here:
        if (this.jRadioButton5.isEnabled()) this.jTextField1.setEnabled(true);
        else this.jTextField1.setEnabled(false);
}//GEN-LAST:event_jRadioButton5StateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
