/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ControlPanel.java
 *
 * Created on Nov 1, 2010, 9:02:43 PM
 */

package sampleboat.gui;

import javax.swing.*;

import sampleboat.control.*;

/**
 *
 * @author Alex
 */
public class ControlPanel extends javax.swing.JPanel {

    protected RobSailBoat boat = null;

    protected JSlider jSlider = null;

    /** Creates new form ControlPanel */
    public ControlPanel() {
        initComponents();
    }

    public void setRobSailBoat(RobSailBoat boat) {
        this.boat = boat;
    }    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider3 = new javax.swing.JSlider();
        jSeparator1 = new javax.swing.JSeparator();
        jSlider2 = new javax.swing.JSlider();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();

        jSlider3.setMajorTickSpacing(100);
        jSlider3.setMaximum(300);
        jSlider3.setMinimum(-300);
        jSlider3.setMinorTickSpacing(50);
        jSlider3.setPaintTicks(true);
        jSlider3.setValue(0);
        jSlider3.setPreferredSize(new java.awt.Dimension(250, 33));
        jSlider3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSlider3MouseReleased(evt);
            }
        });

        jSlider2.setMajorTickSpacing(100);
        jSlider2.setMaximum(800);
        jSlider2.setMinimum(-800);
        jSlider2.setMinorTickSpacing(50);
        jSlider2.setPaintTicks(true);
        jSlider2.setValue(0);
        jSlider2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSlider2MouseReleased(evt);
            }
        });

        jLabel6.setText("Servo 3 (Rudder)");

        jLabel5.setText("Servo 2 (Main)");

        jSlider1.setMajorTickSpacing(100);
        jSlider1.setMaximum(700);
        jSlider1.setMinimum(-700);
        jSlider1.setMinorTickSpacing(50);
        jSlider1.setPaintTicks(true);
        jSlider1.setValue(0);
        jSlider1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSlider1MouseReleased(evt);
            }
        });

        jLabel4.setText("Servo 1 (Jib)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addComponent(jSlider2, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addComponent(jSlider3, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel4)
                .addGap(6, 6, 6)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel5)
                .addGap(6, 6, 6)
                .addComponent(jSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel6)
                .addGap(7, 7, 7)
                .addComponent(jSlider3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setServo(int servo, int increment) {
        switch (servo) {
            case 1 : jSlider = jSlider1; break;
            case 2 : jSlider = jSlider2; break;
            case 3 : jSlider = jSlider3; break;
        }
        increment = increment * -1;
        int newValue = jSlider.getValue() + increment;
        System.out.println(">>> setServo(int) " + servo + "   " + increment);
        if (jSlider != null) {
            if (newValue > jSlider.getMaximum()) jSlider.setValue(jSlider.getMaximum());
            else if (newValue < jSlider.getMinimum()) jSlider.setValue(jSlider.getMinimum());
            else jSlider.setValue(newValue);
            sendBoatData();
        }
    }

    public void setServo(int servo, double value) {
        int newValue = 0;
        switch (servo) {
            case 1 : jSlider = jSlider1; break;
            case 2 : jSlider = jSlider2; break;
            case 3 : jSlider = jSlider3; break;
        }
        if (jSlider != null) {
            int v = (int)(value * jSlider.getMaximum()) * -1;
            newValue += v;
            // first test whether there is any change
            int d = v - jSlider.getValue();
            if (d != 0) {
                if (newValue > jSlider.getMaximum()) jSlider.setValue(jSlider.getMaximum());
                else if (newValue < jSlider.getMinimum()) jSlider.setValue(jSlider.getMinimum());
                else jSlider.setValue(newValue);
                sendBoatData();
            }
        }

    }

    protected void sendBoatData() {
        try {
            boat.sendCommand(new BoatCommand(jSlider3.getValue(), jSlider2.getValue(), jSlider1.getValue()));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void jSlider3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider3MouseReleased
        try {
            boat.sendCommand(new BoatCommand(jSlider3.getValue(), jSlider2.getValue(), jSlider1.getValue()));
        } catch (Exception e) {
            e.printStackTrace();
        }
}//GEN-LAST:event_jSlider3MouseReleased

    private void jSlider2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider2MouseReleased
        try {
            boat.sendCommand(new BoatCommand(jSlider3.getValue(), jSlider2.getValue(), jSlider1.getValue()));
        } catch (Exception e) {
            e.printStackTrace();
        }
}//GEN-LAST:event_jSlider2MouseReleased

    private void jSlider1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider1MouseReleased
        try {
            boat.sendCommand(new BoatCommand(jSlider3.getValue(), jSlider2.getValue(), jSlider1.getValue()));
        } catch (Exception e) {
            e.printStackTrace();
        }
}//GEN-LAST:event_jSlider1MouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JSlider jSlider3;
    // End of variables declaration//GEN-END:variables

}
